permissions:
  contents: write

name: Run Python Script and Commit Changes

on:
  #push:
    #branches:
      #- main   ### 如果这个启动的话，只要有任何对main部分的影响改动就会造成运行
  schedule:
    - cron: '30 0 * * *'  # Runs at 0:30 AM UTC
    - cron: '0 9 * * *' # Runs at 9:00 AM UTC
    #- cron: '15 00 * * *' # Test only
    #- cron: '23 00 * * *' # Test only
    
jobs:
  run-and-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'
          
      - name: Install Google Chrome and ChromeDriver
        uses: browser-actions/setup-chrome@v1
        with:
          chrome-version: 'latest'
          install-dependencies: true
          install-chromedriver: true
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Python script
        run: python AutoPolicy_Ready_V6_Chrome_GitAuto_DynURL.py

      - name: Fetch and merge remote changes
        run: |
          git fetch origin
          git merge origin/main

      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          author_name: 'TG'
          author_email: 'tygao12@outlook.com'
          message: 'Automated commit: Run Python script and update files'
          add: '.'
